### ISSUE TITLE
Feature Request: Multi-entries in the same row

### ISSUE THREAD

**Issue by xu-cheng** [Kapeli/cheatset#17]
I would like to create a cheatsheet of LaTeX math symbols. Something looks like [this](http://web.ift.uib.no/Teori/KURS/WRK/TeX/symALL.html). As you can see, there will be lots of short entries to compose such cheatsheet. So instead of having every entries stand in a separate row, is there an easy way to make them occupy multi columns. Thanks.

**Comment by Kapeli** [comment]
Put them on one row. This is what other cheat sheets do (e.g. HTML Entities). The reasoning would be that they're easier to search for and will also work on mobile device widths.

**Comment by xu-cheng** [comment]
OK.

BTW, I wonder if it's acceptable to put lots of images inside the cheatsheet. In this case, I use image to present the outcome of every LaTeX commands.

**Comment by Kapeli** [comment]
That should be fine.
