### ISSUE TITLE
No support for math typesetting

### ISSUE THREAD

**Issue by solidfox** [Kapeli/cheatset#18]
Would it not be awesome if cheat sheets used something like MathJax to provide support for typesetting math?

**Comment by Kapeli** [comment]
Including MathJax by default wouldn't make sense for most cheat sheets.

I've added support for injecting HTML inside the `<head>` tags of the cheat sheets, so you can include MathJax there.

So, something like this:

```ruby
cheatsheet do
  title 'Sample'
  ...
  resources 'resources_dir' # add MathJax to this dir
  head_inject '<script src="resources_dir/MathJax.js" type="text/javascript"></script>'
  
```
