### ISSUE TITLE
Custom styling override?

### ISSUE THREAD

**Issue by danielbayley** [Kapeli/cheatset#19]
It would be cool if we could override the styling of cheat sheets, maybe with an option in Preferences to choose a custom path to a css file.

**Comment by Kapeli** [comment]
You can define custom styles now. Check out https://github.com/Kapeli/cheatsheets/blob/fbeff4502e4f04d2bc122570a5033f33dcff7881/cheatsheets/Oh-My-Zsh_Git.rb#L6 for an example.

**Comment by danielbayley** [comment]
That's cool, but isn't that *per* cheat sheet? I mean more of a global option that overrides all of them locally.

**Comment by Kapeli** [comment]
Yes, that's per cheat sheet. I don't have any plans for adding global custom styling support right now. Sorry!

**Comment by pmackay** [comment]
@Kapeli is there any way that cheat sheet blocks could be displayed in a 2 or 3-col layout? Particularly on large monitors there is often a large amount of whitespace on the right.

**Comment by Kapeli** [comment]
Not currently, no.

**Comment by Kapeli** [comment]
@danielbayley please email me about it (preferably) with your purchase receipt.

**Comment by danielbayley** [comment]
@Kapeli That's what I can't seem to find… what is your email address? Thanks

**Comment by Kapeli** [comment]
https://kapeli.com/contact
