### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by DaveyD** [Kapeli/cheatset#20]
Hi, I'm a new user of 'Dash' on Windows
I just found that Windows has an app that supports Dash docsets - Velocity and Zeal
I wanted to generate my own cheatsets
Is this possible on Windows? (I see written that xcode is necessary)

Thanks,
David

**Comment by Kapeli** [comment]
No idea...

`cheatset` should work on Windows, but I'm not sure if all of its [dependencies](https://github.com/Kapeli/cheatset/blob/master/cheatset.gemspec#L23-L30) work too. Feel free to try and let me know how it goes.

**Comment by DaveyD** [comment]
Ok, sounds good
Can you please specify what are it's dependencies?

Thanks

**Comment by Kapeli** [comment]
I linked to them in my previous comment.

**Comment by DaveyD** [comment]
Oh... ☺ - Great
Thank you!

**Comment by DaveyD** [comment]
Besides sqlite, I don't even know what any of those things are!  ☺
I guess I'll pass....
Thanks anyway
