### ISSUE TITLE
Stuck on "Parsing documentation...."

### ISSUE THREAD

**Issue by kleerkoat** [Kapeli/cheatset#23]
Installing is getting stuck on "Parsing documentation for cheatset-1.3.4". 

any ideas why? thank you.

**Comment by Kapeli** [comment]
This command should work:

```
sudo gem install cheatset --no-ri --no-rdoc
```

**Comment by kleerkoat** [comment]
that did it! thank you.

**Comment by surfjedi** [comment]
had same problem

**Comment by ihomway** [comment]
That works, thank you @Kapeli
