### ISSUE TITLE
Install halts on parsing

### ISSUE THREAD

**Issue by martynhaigh** [Kapeli/cheatset#24]
When I try to install the gem, the process stops on the parsing stage:

```
sudo gem install cheatset
Password: 
Successfully installed cheatset-1.3.4
Parsing documentation for cheatset-1.3.4
```
I've left this for a good few hours with no further output.

zshell & bash on a MBP running latest Sierra 10.12.4

**Comment by Kapeli** [comment]
This command should work:

```
sudo gem install cheatset --no-ri --no-rdoc
```
