### ISSUE TITLE
Type and Name use different vertical orientation

### ISSUE THREAD

**Issue by vr8hub** [Kapeli/cheatset#27]
I am working on something where I want command, name, and notes to be in separate columns. Thus my .rb file looks something like this:

```
    entry do
      command 'command'
      name 'name'
      td_notes <<-'END'
        Some text describing the code about to display

        ```
        some code
        ```

        Some more text describing the next set of code. This might be a length description, so it might wrap to a couple of lines or more when displayed in Dash.

        ```
        some code
        ```
      END
    end
```

The problem with the above is that Dash renders "command" at the *top* of the first column, while "name" appears *centered* in the second column. This is visually very jarring, and makes it hard to read.
It would be more aesthetically pleasing (and easier to read) if they were both using the same orientation, i.e. both at the top, or both centered. (I would personally choose centered.) Even if there were multiple commands (I'm not going to have that, but I understand the need to support it), they could still be centered vertically within the space.

Thanks!

**Comment by vr8hub** [comment]
It occurred to me that I might be able to change this with custom CSS in style. I've searched the web for vertically aligning text in a cell, and played around with several methods for a while, but I'm apparently not smart enough. :)
The problem (for me) is that the rows are variable height, and the command is made up of `<code>` within a `<p>` within the td (class "command"), and there can be multiple of the `<p><code>' pairs. With all of that, my CSS-fu  is not nearly good enough to figure it out.

**Comment by vr8hub** [comment]
You waited long enough. :) I first tried the obvious:
```css
.command {
    vertical-align: middle;
}
```
When that didn't work, I went spelunking on the web and tried a number of other things.

Today I thought to copy the entire style.css to jsfiddle and just mess around. I noticed that the td.command block had a vertical alignment in it (albeit "top"), so I changed mine to include the td. And it worked.
```css
td.command {
    vertical-align: middle;
}
```

I'm still not smart enough to know why it didn't work before (I didn't think a class had to have its parent included). But I figured out what I needed, so I think I'm good. Sorry for the noise.

**Comment by Kapeli** [comment]
Thanks for letting me know about this. I'm going to fix it by making the name `vertical-align:top` as well.

> I'm still not smart enough to know why it didn't work before (I didn't think a class had to have its parent included). But I figured out what I needed, so I think I'm good. Sorry for the noise.

I think it has to do with CSS [Specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).

**Comment by Kapeli** [comment]
I've reverted the fix, as it doesn't look good in the case below (which is most common). This is something that will have to be fixed with custom CSS, on a per-cheatsheet basis.

![screen shot 2018-04-06 at 18 28 43](https://user-images.githubusercontent.com/1445635/38430088-ee9afac6-39c8-11e8-9dfc-12432851199e.png)

**Comment by vr8hub** [comment]
No, I agree, I think you need to change the vertical-align of command to middle. :) That's what I was looking for (and what I did).
In your example, it won't matter, since command is the tallest of the two, so the alignment doesn't matter. But when it's not, i.e. when there is more in name/notes than in command, it looks just as bad (IMO) for command to be top-aligned and name/notes to be middle aligned.

But, either way, I have my custom CSS working, so I'm good.

**Comment by Kapeli** [comment]
Having the command middle-aligned isn't really an option due to entries that are really large (i.e. the user would have to scroll to see the command).

**Comment by vr8hub** [comment]
Just like we do now for the name. :) That's my point — it doesn't much sense for one thing to be middle aligned and the other not. They should both be one or the other.

**Comment by Kapeli** [comment]
Aligning commands to top makes sense in this case:

![screen shot 2018-04-06 at 21 31 41](https://user-images.githubusercontent.com/1445635/38438134-437b9e1a-39e2-11e8-830f-28abcd31b087.png)

By the way, for your cheat sheet, why not add the notes below the name instead of a separate column?

**Comment by vr8hub** [comment]
This is why design, like music, tends to be very personal. :) For me, it doesn't make sense for two side-by-side columns to have different vertical alignment. It's aesthetically ugly (again, to me). Just like you didn't like the looks of top-aligning the name column (which I agree with), I don't like the looks of either of them being different than the other. (I never have liked the way Excel handles this type of situation, either.)

I have three distinct pieces of information I'm communicating. I want them in three columns. (See above. :) )
