### ISSUE TITLE
small error in installation command 

### ISSUE THREAD

**Issue by stepvda** [Kapeli/cheatset#30]
the [README.MD](https://github.com/Kapeli/cheatset/blob/master/README.md) specifies the command line options `--no-ri` and `--no-rdoc`. 
This would not work on my mac but as it turns out there should only a sinlge dash instead of two in front of each option `-no-ri` and `-no-rdoc`. 

This is therefore the command I had to use:
````bash
sudo gem install cheatset -no-ri -no-rdoc
````

While I'm at it, here's a quick side note, from me not being a big _gem_ or _ruby_ user.  I had another issue first that talked about SSL certif issues. As it turns out my version of ruby was outdated and didn't have valid root CA certifs anymore. Doing a `brew install ruby`
(for more on this issue see this [reference](https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors)).
On my MacBookPro I was expecting the same issue and it looked that way but there  a fast `brew link ruby` was enough. Homebrew will also tell you to add the ruby directory to your $PATH if that's not yet the case.
You can check all is good with this command: `ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'`

**Comment by Kapeli** [comment]
What macOS version are you using?
