### ISSUE TITLE
Is it possible to turn off markdown?

### ISSUE THREAD

**Issue by holyjak** [Kapeli/cheatset#36]
Hi! My cheat sheet's `notes` have non-trivial HTML content and is screwed up when cheatset tries to be helpful and interpret parts of it as Markdown. Is there a way to prevent that? Thank you!

Examples:

* I have HTML `<code>*bold*</code>` and expect to see `*bold*`, instead I see *bold*

This html:

    <code>```&lt;language&gt; ... ```</code>

is displayed as `&lt;language&gt; ...` instead of:

    ```<language> ... ```

This HTML:

        <pre>[source]
        ----
        clojure, SQL     ;  <b class="conum">(1)</b>
        C-like           // <b class="conum">(2)</b>
        Python etc.      #  <b class="conum">(3)</b>
        XML              &lt;!--<b class="conum">(4)</b>--&gt;
        # Include from a file, specific lines only (-1 = until the end):
        include::filename.txt[lines=7;14..25;30..-1]
        
        # or include regions between tags; also, un-indent:
        include::lib/app.rb[tag=mytag,indent=0]
        ----
        &lt;1&gt; callout
        &lt;2&gt; callout
        &lt;3&gt; callout
        &lt;4&gt; callout</pre>

is turned into something completely different:

        <p></p>
        
        <h2><pre>[source]</pre></h2>
        
        <p>clojure, SQL     ;  <b class="conum">(1)</b>
        C-like           // <b class="conum">(2)</b>
        Python etc.      #  <b class="conum">(3)</b>
        XML              &lt;!--<b class="conum">(4)</b>--&gt;</p>
        
        <h1>Include from a file, specific lines only (-1 = until the end):</h1>
        
        <p>include::filename.txt[lines=7;14..25;30..-1]</p>
        
        <h1>or include regions between tags; also, un-indent:</h1>
        
        <h2>include::lib/app.rb[tag=mytag,indent=0]</h2>
        
        <p>&lt;1&gt; callout
        &lt;2&gt; callout
        &lt;3&gt; callout
        &lt;4&gt; callout
        </p>

and screws up totally the formatting of the rest of the document.

**Comment by holyjak** [comment]
Actually, I likely should not have been using the library at all. I could use it to generate an empty cheatsheet and then just paste my content into the index.html. So my question should rather be:

> What is required of the cheatsheet index.html to be a correct cheat sheet from Dash's point of view?

**Comment by holyjak** [comment]
Hm, How do I create <my>.docset/Contents//Resources/docSet.dsidx? Or rather, what should be inside the sqlite db?

**Comment by holyjak** [comment]
I found the how-to create docsets docs, which I suppose apply the same to cheat sheets, because they are no different from docsets, right?

**Comment by holyjak** [comment]
I do not know why this processing of markdown inside HTML happens. IT seems cheatset uses Redcarpet and according to https://github.com/vmg/redcarpet/issues/13#issuecomment-1054113 it does not and *should not* do this.

**Comment by holyjak** [comment]
Sample cheat sheet with the problem - [AsciiDoctor.rb.txt](https://github.com/Kapeli/cheatset/files/7266607/AsciiDoctor.rb.txt)

Look at the notes in the entries `'Source code listing' (screwed up pre) and `'Text Formatting'` (screwed up `*bold*` etc.). You can compare it against https://github.com/holyjak/dash-asciidoc-cheatsheet/releases/download/2.0.16%2Falpha/index.html (which is from a little older version so not 100% match but good enough)

**Comment by holyjak** [comment]
Hi @Kapeli ! Any update on how to resolve this? Did the example of a cheat sheet I posted above help? Thank you!

**Comment by Kapeli** [comment]
Sorry for the wait. I've looked into it and I have no idea why redcarpet processes the Markdown inside the HTML. https://github.com/vmg/redcarpet/issues/13#issuecomment-1054113 is 10 years old, so maybe things have changed since.

I've added an `html_notes` option in cheatset 1.4.4 which doesn't process markdown at all. So within entries instead of using `notes`, use `html_notes`.

**Comment by holyjak** [comment]
Thank you! I have used it in https://github.com/Kapeli/cheatsheets/pull/404
